# This is a config for E2B sandbox template.
# You can use template ID (pgmlnle9917q1dsqgcrj) or template name (vibe-nextjs-testfk003) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-testfk003") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-testfk003") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-testfk003')

team_id = "10df7239-31d9-4218-964f-9d6bfdc9582c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-testfk003"
template_id = "pgmlnle9917q1dsqgcrj"
